[params.author]
  name = "Treanungkur Mal"
  image = "img/logo.jpg"
  headline = "Graduate Student at the University of Washington"
  bio = "Graduate Student in Mathematics."
  links = [
    { email = "mailto:maltreanungkur@gmail.com" },
    { github = "https://github.com/maltreanungkur" },
    { instagram = "https://instagram.com/treanungkur.mal" },
    { x-twitter = "https://x.com/mal_treanungkur" },
    { google-scholar = "https://scholar.google.com/citations?user=YPAVE68AAAAJ&hl=en" },
    # { orcid = "https://orcid.org/" },
    # { researchgate = "" },
  ]
